<h3>Coming soon...</h3>
<p>
  <ul>
    <li>
      <b><em>Heliconius melpomene</em> expert annotations</b>
    </li>
    <li>
      <b><em>Bicyclus anynana</em> preliminary assembly and annotations</b>
    </li>
    <li>
      <b>Lepidoptera-specific orthologue predictions and gene trees</b>
    </li>
    <li>
      <b>Variations</b>
    </li>
    <li>
      <b>Improved search result display</b>
    </li>
    <li>
      <b>More genomes</b>
    </li>
  </ul>
</p>