<div class="plain-box"><h2>What's new</h2>
  <div class="info-box embedded-box float-right">
    <h3>More from LepBase...</h3>
    <p>We aim to provide a comparative genomics resource for the Lepidotera research 
      community, of which this ensembl instance is only the beginning, visit 
      <a href="http://lepbase.org" title="lepbase.org">lepbase.org</a> to find out more about the project.
    </p>
  </div>
  <p>This is the first release of the LepBase ensembl genome browser, building upon the 
    Lepidopteran content already available through <a href="http://metazoa.ensembl.org" 
    title="metazoa.ensembl.org">Ensembl Metazoa</a> to deliver the datasets and analyses 
    of most value to the Lepidoptera community.  If there is something missing that you 
    would like to see then please <a href="mailto:contact@lepbase.org" 
    title="contact@lepbase.org">contact us</a>. 
  </p>
  <p>
    New data in version 0.5 include:
  </p>
  <ul>
    <!--li>
      <b><em>Bicyclus anynana</em></b>
      <br/>preliminary assembly and annotations
    </li--> 
    <li>
      <b><em>Bombyx mori</em></b>
      <br/>NCBI RefSeq gene models and annotations
    </li> 
    <!--li>
      <b><em>Heliconius melpomene</em></b>
      <br/>expert annotations
    </li--> 
    <li>
      <b><em>Plutella xylostella</em></b>
      <br/>BGI assembly and annotations
    </li> 
    <li>
      <b>All species</b>
      <br/>Linking annotations to gene descriptions to make putative gene functions easier to identify and allow text search for more genes.
    </li> 
  </ul>
</div>
