<div class="plain-box"><h2>What's new</h2>
  <div class="info-box embedded-box float-right">
    <h3>More from Lepbase...</h3>
    <p>We aim to provide a comparative genomics resource for the Lepidotera research 
      community, with BLAST and WebApollo servers in addition to this Ensembl instance, visit 
      <a href="http://lepbase.org" title="lepbase.org">lepbase.org</a> or follow @lepbase to find out more about the project.
    </p>
  </div>
  <p>This is version 1.0 of the Lepbase ensembl genome browser.
     New features include a dedicated BLAST server, Lepidoptera-specific orthologue predictions &amp; gene trees, and WebApollo for community annotation.  If there is something missing that you 
    would like to see then please <a href="mailto:contact@lepbase.org" 
    title="contact@lepbase.org">contact us</a>. 
  </p>
  <p>
    New species/assemblies in version 1.0:
  </p>
  <ul>
    <li>
      <em>Chilo suppressalis</em> CsuOGS1.0
    </li> 
    <li>
      <em>Heliconius melpomene</em> Hmel2
    </li> 
    <li>
      <em>Lerema accius</em> v1.1
    </li> 
    <li>
      <em>Manduca sexta</em> Msex_1.0
    </li> 
    <li>
      <em>Papillio glaucus</em> v1.1
    </li> 
    <li>
      <em>Pieris napi</em> DAS5
    </li> 
    <li>
      <em>Plodia interpunctella</em> v1
    </li>  
    <li>
      18 Heliconiine DISCOVAR assemblies
    </li>  
  </ul>
</div>
